[phases.setup]
nixPkgs = ["nodejs_22", "pnpm", "g++", "make", "python3"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile", "pnpm rebuild better-sqlite3"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node server/server.js"
