import type { AccidentReport } from "./types";
import { generateCroquis } from "./croquisGenerator";

const MOCK_POST_IMPACT = {
  driftDirection: "none" as const,
  driftAngleDeg: 0,
  driftMagnitudeG: 0,
  stabilizationTimeMs: 0,
  secondaryImpacts: 0,
  postImpactRotation: false,
  postImpactYawRate: 0,
  vehicleStoppedImmediately: false,
  postCrashDecelG: 0,
  directionConfirmed: false,
  score: 0,
  factorsAr: [],
};

const RAW_MOCK_REPORTS: AccidentReport[] = [
  {
    id: "demo_report_1",
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 2, // 2 days ago
    syncStatus: "synced",
    peakGForce: 3.8,
    jerkPeak: 12.5,
    impactZone: "rear",
    impactDirection: "rear",
    speedKmh: 0,
    preCrashSpeedKmh: 0,
    speedHistory: [0, 0, 0, 0, 0],
    latitude: 24.7136,
    longitude: 46.6753,
    severity: "severe",
    liabilityScore: 0,
    confidence: "high",
    scenarioCode: "REAR_END_STATIONARY",
    scenarioAr: "صدم من الخلف أثناء التوقف",
    descriptionAr: "المركبة كانت متوقفة تماماً وتعرضت لصدمة قوية من الخلف. المؤشرات تدل على أن الطرف الآخر هو المتسبب بالحادث لعدم ترك مسافة آمنة.",
    factorsAr: ["مركبة متوقفة (السرعة 0 كم/س)", "صدمة مباشرة من الخلف", "قوة G عالية (3.8g)"],
    feedback: null,
    gyroscope: {
      peakRotationRate: 15,
      spinDetected: false,
      dominantAxis: "pitch",
      yawRate: 2,
      pitchRate: 15,
      rollRate: 1,
      rolloverDetected: false,
    },
    braking: {
      brakingDetected: false,
      brakingDurationSec: 0,
      decelerationG: 0,
      speedBeforeBraking: 0,
    },
    confidenceDetails: {
      level: "high",
      score: 95,
      factors: ["السرعة صفر", "اتجاه الصدمة واضح"],
    },
    impactCount: 1,
    baselineG: 1.0,
    sessionDurationAtCrash: 1200,
    otherParty: {
      approachAngleDeg: 180,
      estimatedSpeedKmh: 45,
      impactForce: "heavy",
      vehicleType: "medium",
      wasAccelerating: false,
      wasBraking: true,
      confidencePercent: 88,
      descriptionAr: "الطرف الآخر كان يقترب من الخلف بسرعة متوسطة إلى عالية، وحاول الفرملة متأخراً.",
    },
    croquis: null,
    matchedAccidentId: "mock_match_123",
    matchConfidence: 92,
    advancedAnalysis: {
      angularStability: { hadSuddenYaw: false, wasEvasive: false, maxYawRatePreCrash: 0, score: 0 },
      multiVector: { lateralG: 0.2, longitudinalG: 3.8, rearPushRatio: 0.9, score: -20 },
      roadContext: { roadType: "urban", hasPriority: true, wasStationary: true, confirmedByGyro: true, score: -20 },
      microKinematic: { scrapeDetected: false, highFreqVariance: 2.1, jerkGyroSync: true, vibrationDurationMs: 150, score: 0 },
      preCrashEvents: { hardBraking: false, hardAcceleration: false, steadyDriving: true, evasiveManeuver: false, score: -10 },
      postImpact: MOCK_POST_IMPACT,
      totalAdjustment: -50,
      discoveredFactorsAr: ["توقف تام للمركبة", "دفع أمامي مفاجئ"],
    },
    crossVerifiedId: "cv_123",
    crossVerifiedAnalysis: {
      id: "cv_123",
      accident_a_id: "demo_report_1",
      accident_b_id: "demo_report_1_other",
      verified_impact_zone_a: "rear",
      verified_impact_zone_b: "front",
      verified_speed_a_kmh: 0,
      verified_speed_b_kmh: 40,
      first_contact_party: "B",
      consistency_status: "VERIFIED",
      consistency_flags: [],
      liability_a_percent: 0,
      liability_b_percent: 100,
      created_at: Date.now() - 1000 * 60 * 60 * 24 * 2,
    }
  },
  {
    id: "demo_report_2",
    timestamp: Date.now() - 1000 * 60 * 60 * 5, // 5 hours ago
    syncStatus: "synced",
    peakGForce: 2.5,
    jerkPeak: 8.2,
    impactZone: "front-left",
    impactDirection: "front",
    speedKmh: 85,
    preCrashSpeedKmh: 105,
    speedHistory: [105, 100, 95, 90, 85],
    latitude: 24.7236,
    longitude: 46.6853,
    severity: "severe",
    liabilityScore: 100,
    confidence: "high",
    scenarioCode: "FRONTAL_SPEEDING",
    scenarioAr: "اصطدام أمامي مع سرعة زائدة",
    descriptionAr: "المركبة كانت تسير بسرعة تتجاوز الحد المسموح وحاولت الفرملة بقوة قبل الاصطدام بزاوية أمامية. نسبة الخطأ بالكامل على السائق.",
    factorsAr: ["سرعة زائدة (105 كم/س)", "فرملة قوية مفاجئة", "انحراف زاوي قبل الاصطدام"],
    feedback: "correct",
    gyroscope: {
      peakRotationRate: 45,
      spinDetected: true,
      dominantAxis: "yaw",
      yawRate: 45,
      pitchRate: 10,
      rollRate: 5,
      rolloverDetected: false,
    },
    braking: {
      brakingDetected: true,
      brakingDurationSec: 2.5,
      decelerationG: 0.8,
      speedBeforeBraking: 105,
    },
    confidenceDetails: {
      level: "high",
      score: 90,
      factors: ["سرعة عالية موثقة", "بيانات الفرملة واضحة"],
    },
    impactCount: 1,
    baselineG: 1.0,
    sessionDurationAtCrash: 450,
    otherParty: {
      approachAngleDeg: 45,
      estimatedSpeedKmh: 20,
      impactForce: "moderate",
      vehicleType: "light",
      wasAccelerating: false,
      wasBraking: false,
      confidencePercent: 75,
      descriptionAr: "الطرف الآخر كان يسير ببطء أو يعبر التقاطع.",
    },
    croquis: null,
    matchedAccidentId: null,
    matchConfidence: null,
    advancedAnalysis: {
      angularStability: { hadSuddenYaw: true, wasEvasive: true, maxYawRatePreCrash: 35, score: 10 },
      multiVector: { lateralG: 1.5, longitudinalG: 2.5, rearPushRatio: 0.1, score: 20 },
      roadContext: { roadType: "highway", hasPriority: false, wasStationary: false, confirmedByGyro: true, score: 20 },
      microKinematic: { scrapeDetected: false, highFreqVariance: 3.5, jerkGyroSync: true, vibrationDurationMs: 200, score: 0 },
      preCrashEvents: { hardBraking: true, hardAcceleration: false, steadyDriving: false, evasiveManeuver: true, score: 0 },
      postImpact: MOCK_POST_IMPACT,
      totalAdjustment: 50,
      discoveredFactorsAr: ["سرعة عالية", "فقدان السيطرة والانحراف"],
    },
  },
  {
    id: "demo_report_3",
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 14, // 2 weeks ago
    syncStatus: "synced",
    peakGForce: 2.1,
    jerkPeak: 6.5,
    impactZone: "side-right",
    impactDirection: "side-right",
    speedKmh: 45,
    preCrashSpeedKmh: 45,
    speedHistory: [45, 45, 45, 45, 45],
    latitude: 24.6936,
    longitude: 46.6553,
    severity: "moderate",
    liabilityScore: 50,
    confidence: "medium",
    scenarioCode: "SIDE_INTERSECTION",
    scenarioAr: "تصادم جانبي في تقاطع",
    descriptionAr: "تصادم جانبي ناتج عن دخول تقاطع في نفس الوقت مع مركبة أخرى. المسؤولية مشتركة بناءً على غياب الأولوية الواضحة.",
    factorsAr: ["تصادم جانبي أيمن", "سرعة منتظمة", "غياب مؤشرات الفرملة"],
    feedback: null,
    gyroscope: {
      peakRotationRate: 60,
      spinDetected: true,
      dominantAxis: "roll",
      yawRate: 20,
      pitchRate: 5,
      rollRate: 60,
      rolloverDetected: false,
    },
    braking: {
      brakingDetected: false,
      brakingDurationSec: 0,
      decelerationG: 0,
      speedBeforeBraking: 45,
    },
    confidenceDetails: {
      level: "medium",
      score: 70,
      factors: ["تأرجح جانبي قوي", "لا توجد فرملة استباقية"],
    },
    impactCount: 1,
    baselineG: 1.0,
    sessionDurationAtCrash: 300,
    otherParty: {
      approachAngleDeg: 90,
      estimatedSpeedKmh: 40,
      impactForce: "moderate",
      vehicleType: "medium",
      wasAccelerating: true,
      wasBraking: false,
      confidencePercent: 82,
      descriptionAr: "الطرف الآخر دخل التقاطع من الجهة اليمنى بسرعة ثابتة.",
    },
    croquis: null,
    matchedAccidentId: null,
    matchConfidence: null,
    advancedAnalysis: {
      angularStability: { hadSuddenYaw: false, wasEvasive: false, maxYawRatePreCrash: 5, score: 0 },
      multiVector: { lateralG: 2.1, longitudinalG: 0.5, rearPushRatio: 0.0, score: 0 },
      roadContext: { roadType: "intersection", hasPriority: false, wasStationary: false, confirmedByGyro: true, score: 0 },
      microKinematic: { scrapeDetected: true, highFreqVariance: 4.2, jerkGyroSync: true, vibrationDurationMs: 300, score: 0 },
      preCrashEvents: { hardBraking: false, hardAcceleration: false, steadyDriving: true, evasiveManeuver: false, score: 0 },
      postImpact: MOCK_POST_IMPACT,
      totalAdjustment: 0,
      discoveredFactorsAr: ["تصادم في تقاطع", "احتمالية حكة جانبية طويلة"],
    },
  }
];

export const MOCK_REPORTS: AccidentReport[] = RAW_MOCK_REPORTS.map(report => ({
  ...report,
  croquis: generateCroquis(report, report.otherParty ?? null),
}));
